### ISSUE TITLE
Automate the ORAS upgrade in package manager systems

### ISSUE THREAD

**Issue by FeynmanZhou** [oras-project/oras#1025]
### What is the version of your ORAS CLI

v1.1.0-rc.1

### What would you like to be added?

From the [installation guide](https://oras.land/docs/how_to_guides/installation/), Homebrew, Winget, Nix, and Snap only support ORAS v1.0.0 so far. We need to investigate and find approaches to automate the ORAS upgrade in those package manager systems.

- [x] Homebrew: it will be automatically upgraded in the package manager when a new ORAS release is out
- [ ] Winget: it is tracked in #939 
- [x] Nix: need to investigate how to add this upgrade to GitHub Actions of the release process
- [ ] Snap:   need to investigate how to add this upgrade to GitHub Actions of the release process
    - [x] https://github.com/oras-project/oras/issues/1052

### Why is this needed for ORAS?

It will be convenient for ORAS maintainers to maintain the ORAS upgrade in those package manager systems. Users can install the latest version of ORAS CLI on each OS/platform easier. 

### Are you willing to submit PRs to contribute to this feature?

- [ ] Yes, I am willing to implement it.

**Comment by amands98** [comment]
Hi @FeynmanZhou , I can help investigate some of these items.

**Comment by amands98** [comment]
Homebrew : https://github.com/marketplace/actions/bump-homebrew-formula

**Comment by FeynmanZhou** [comment]
Thanks @amands98 ! We will review #1033.

**Comment by FeynmanZhou** [comment]
I also assigned this issue to you @amands98

**Comment by FeynmanZhou** [comment]
@developer-guy Do you know how to automate the [ORAS package](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/tools/oras/default.nix) update in Nix?

**Comment by shizhMSFT** [comment]
Thank @amands98 for sending out PRs. However, we need to discuss before proceeding the PR review.

In general, upgrading packages in a package manager requires an account of that system. For example, homebrew is based on GitHub so that it requires a GitHub account to do the commit. Other package managers may require differently.

The ultimate question is: Who should be the committer? It should be trusted and should not be an account of a real person (otherwise, that person is risk of impersonation).

**Comment by FeynmanZhou** [comment]
> Thank @amands98 for sending out PRs. However, we need to discuss before proceeding the PR review.
> 
> In general, upgrading packages in a package manager requires an account of that system. For example, homebrew is based on GitHub so that it requires a GitHub account to do the commit. Other package managers may require differently.
> 
> The ultimate question is: Who should be the committer? It should be trusted and should not be an account of a real person (otherwise, that person is risk of impersonation).

Maybe we can use a bot account to handle this process. We will come up with a solution and update here

**Comment by shizhMSFT** [comment]
Meanwhile, we found that podman desktop has done similar job to publish releases to various package manager systems, including but not limited to `brew` (homebrew) and `winget`. We can take it as reference to develop our own release pipeline.

Reference: https://github.com/containers/podman-desktop/tree/main/.github/workflows

**Comment by shizhMSFT** [comment]
More comments on `brew` (homebrew)
----
Unlike podman desktop, which is a brew cask, `oras` is a brew formula. Therefore, we cannot directly copy the workflow from podman deslop.

We SHOULD use the `brew` CLI on macOS to up to ensure the resulted formula is workable on a Mac. Detailed instruction can be found at [Updating Software in Homebrew](https://docs.brew.sh/Updating-Software-in-Homebrew) and [Submit a new version of an existing formula](https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request#submit-a-new-version-of-an-existing-formula). Basically, sending out a formula PR for a new version of `oras` is as simple as running `brew bump-formula-pr`. Since the `brew` CLI is always update-to-date, we will have less chance to get errors or the bump up PR is requested for changes by the brew maintainers.

**Comment by shizhMSFT** [comment]
More comments on `winget`
---
There is a tool named [winget-create](https://github.com/microsoft/winget-create) by Microsoft Official. It does not require the user to fork the `winget-pkgs` repo to the organization.

**Comment by FeynmanZhou** [comment]
@amands98 Could you please help investigate solutions for `brew` and `winget` from @shizhMSFT 's proposal?

**Comment by developer-guy** [comment]
There is a bot called [r-ryantm](https://github.com/r-ryantm), thanks to @ryantm, it regularly updates Nix packages based on the [nixpkgs-update](https://github.com/ryantm/nixpkgs-update) project. I guess we don't need to do anything special on the Nix side to update oras packages, all we need to do is check the update PR and approve it if everything looks good, @ryantm can correct me if I'm wrong.

**Comment by FeynmanZhou** [comment]
Thanks @developer-guy . I saw ORAS CLI was upgraded to v1.0.1 by this PR  https://github.com/NixOS/nixpkgs/pull/247693#event-10021490132. 

From the [Nix doc](https://ryantm.github.io/nixpkgs-update/r-ryantm/#r-ryantm), they have a bot account that updates Nixpkgs by making PRs that bump a package to the latest version. So no further actions that we need to take in ORAS.

cc @oras-project/oras-cli

**Comment by developer-guy** [comment]
we can close this one as we don't need to take manual actions or don't need to anything to automate this process since the we have already have an automation on that.
