### ISSUE TITLE
--artifact-type 'sbom' for oras push fails with v1.1.0

### ISSUE THREAD

**Issue by ncheneweth** [oras-project/oras#1120]
### What happened in your environment?

oras push --artifact-type 'sbom' docker.io/$(cat manifestid | sed 's/docker.io\///g' | sed 's/:/-/g' | sed 's/@/:/g').spdx sbom.spdx:application/json
Error: invalid artifactType format: sbom: invalid media type

### What did you expect to happen?

This works in v1.0.0

### How can we reproduce it?

Generate manifest for image:

docker image inspect --format='{{index .RepoDigests 0}}' IMAGE_NAME > manifestid

create sbom using syft:

syft packages --verbose --output spdx-json $(cat manifestid) > sbom.spdx

Attempt to push to dockerhub

oras push --artifact-type 'sbom' docker.io/$(cat manifestid | sed 's/docker.io\///g' | sed 's/:/-/g' | sed 's/@/:/g').spdx sbom.spdx:application/json

### What is the version of your ORAS CLI?

v1.1.0

### What is your OS environment?

MacOC Ventura 13.5.2

### Are you willing to submit PRs to fix it?

- [ ] Yes, I am willing to fix it.

**Comment by qweeah** [comment]
This is by design. `sbom` is not compliant to [RFC 6838](https://tools.ietf.org/html/rfc6838) and thus not a valid artifact type. For detail, see the `artifactType` bullet point in [oci spec 1.1.0-rc.4](https://github.com/opencontainers/image-spec/blob/v1.1.0-rc4/manifest.md#image-manifest-property-descriptions). 

This check was introduced on SDK side in oras-go 2.3.0 (see https://github.com/oras-project/oras-go/issues/571) and that's why it's not reflected in our release notes.

**Comment by qweeah** [comment]
@ncheneweth The mentioned OCI spec requires artifact type to at least contain a `/`, can you try with `--artifact-type application/sbom+json` and let us know if it's working? Thanks
