### ISSUE TITLE
Document use with GitLab Container Registry

### ISSUE THREAD

**Issue by mykter** [oras-project/oras#260]
Following the README works for logging in, but then when it comes to pushing you hit a 500 error:
```
$ oras push gitlab-docker-registry.example.com/group/project/artifact:latest --manifest-config /dev/null:application/vnd.acme.rocket.config artifact.txt
Uploading c0f7203dcc57 artifact.txt
Error: failed commit on ref "unknown-sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855": unexpected status: 500 Internal Server Error
```

However if you remove the `--manifest-config` option it works.

I don't know if this is a bug on the GitLab front (I couldn't [see anything](https://gitlab.com/gitlab-org/gitlab/-/issues?scope=all&utf8=%E2%9C%93&state=opened&search=%22container+registry%22+oci)) or if this is reasonable and just needs documenting.

**Comment by mahendrapaipuri** [comment]
I was trying to push Singularity image into GitLab registry and this worked for me:

`oras push registry.gitlab.com/group/project/images/my-img my-img.sif:appliciation/vnd.sylabs.sif.layer.tar`

Looks like I just have to specify the layer type.

I could pull this image as well without any issues. The only problem is that GitLab container registry UI parses the `creation` timestamp of the config file to show the publish time. Apparently there is no `creation` timestamp available on the config file and image tag always says that it is published "just now". I am not sure if the problem is on `oras` side or GitLab side.

**Comment by dtrudg** [comment]
It appears GitLab Container registry has the same issue we see (in Singularity) with Harbor. The registry rejects the null config as it has a non-oci image config media type.

In https://github.com/hpcng/singularity/pull/5951 - we are just going to try to push SIF images to a registry using the custom config mediatype, and then if it fails try again without. This should be an effective fix for `singularity push` to GitLab and Harbor, though it's not very pretty.

We want to push the null config with specific config mediatype whenever possible, because of the note at the bottom of:

https://github.com/deislabs/oras/blob/main/docs/config.md#arbitrary-config-media-type

... which indicates the custom config media type ensures docker and oci image clients shouldn't pull the layers before finding out they aren't usable.

My thinking is that any registry that is oras compatible should allow this?

**Comment by sajayantony** [comment]
From the above discussion this appears to be a GitLab Container Registry specific issue. Please consider reopening the issue if there is any specific action that needs to be taken on the ORAS-go or ORAS CLI side.
