### ISSUE TITLE
Merge features in `artifacts` branch as experimental features

### ISSUE THREAD

**Issue by shizhMSFT** [oras-project/oras#379]
With `oras-go` v2, we can "merge" (re-implement) those features in the `artifacts` branch into `main` with those features marked as experimental.

Features:
- [x] `oras discover`.
- [x] `oras push` artifact manifest.
- [x] `oras pull` artifact manifest.

**Comment by shizhMSFT** [comment]
@qweeah You may create issues according to this issue.

**Comment by qweeah** [comment]
ack

**Comment by qweeah** [comment]
# Implementation Gaps
## Pull
This command is already provided in the main branch. Below options are new in the `artifacts` branch:
- `media-type` and `allow-all`: Since we have already removed the metia-type filtering features in https://github.com/oras-project/oras/issues/130, those options are deprecated.
- `allow-empty-name`: File target already support in-memory caching for non-named manifests.

Basically there is no implementation effort required for the pull command.

## Discover
This is a new command, we need to support discovering artifacts linked with a specified reference, with optional artifact type filtering and different formats of output.

## Push
This command is already provided in the main branch. Below options are new in the `artifacts` branch:
- `manifestExport`: User will use this to save the packed manifest to a local file. We will refetch the manifest from the source file target and write to a file.  It would be better 

- `subject` and `artifact-type`: those two options will be removed and re-implemented in #424

**Comment by shizhMSFT** [comment]
Closed by #419 and #425
