### ISSUE TITLE
Add issue and PR template for the ORAS repositories

### ISSUE THREAD

**Issue by FeynmanZhou** [oras-project/oras#477]
To make ORAS Pull Request and issue clear and traceable, I propose adding a Pull Request and issue template for the ORAS repositories.

## Issue Template

Currently, I think these three types of issue template are enough for the ORAS community:
- Bug Report
```
- What happened in your environment?

- What did you expect to happen?

- How can we reproduce it (Please tell us your environment information as minimally and precisely as possible)?

- ORAS CLI version

- OS version
```
- Feature Request
```
- What would you like to be added?

- Why is this needed? Please describe your user story or scenario.

```
- Support
```
- What's your question?

- Environment: OS Information

- Error logs or messages (Attach logs or screenshots)

- ORAS CLI Version
```

## PR Template
The PR template will include the following questions:

```
- What type of PR is this? 

- What this PR does / why we need it:

- Which issue(s) this PR fixes:

Fixes #

- Does this PR introduce a user-facing change? Is it necessary to update the documentation? 

- Additional documentation or context, e.g, Proposals, GitHub discussion, usage docs, etc.:
```

**Comment by vsoch** [comment]
@FeynmanZhou great idea! When we ask for specific information (e.g., versions) I would put in a bulleted list, like:

```
- **ORAS CLI version**:
- **What registry are you using?**:
- **OS Version**:
```
And rendered:

- **ORAS CLI version**:
- **What registry are you using?**:
- **OS Version**:

It's technically the same information, but in this form it (visually) seems like less than the large sections. And I removed the example registry names because I suspect people will be able to answer without it - we could add  back if it seems like there isn't enough guidance for the question.

**Comment by FeynmanZhou** [comment]
> 

@vsoch  Okay. Thanks for your good suggestion! I will remove the registry from the issue list.

**Comment by qweeah** [comment]
@FeynmanZhou Thanks for the effort. All templates look good and are exactly what we need.
