### ISSUE TITLE
ORAS pull manifest config: rename the --manifest-config to --config

### ISSUE THREAD

**Issue by lizMSFT** [oras-project/oras#495]
Since issue https://github.com/oras-project/oras/issues/362 and PR https://github.com/oras-project/oras/pull/468 have supported manifest annotation flags via `--annotations`. We could also simply `oras pull --manifest-config` to just `oras pull --config`.

Note: 
`--config` is already reserved for auth config. We need to use another flag name for auth config.

Discussion: https://github.com/oras-project/oras/pull/480#issuecomment-1213046895

**Comment by sajayantony** [comment]
Looking at other clients - 

Having a good name for oras-config file both as an environment variable and a qualified flag aligns nicely with other tools shown below. 
Instead of auth config we could just name this `orasconfig` or `oras-config` If we have other default options like host level mappings for say localhost:5000 use `plainHttp`, these kinds of settings can be placed in the config file and we don't need to pass in these flags always. 

### Kubectl
- KubeConfig even support an environment variable which can be used to load the kubeconfig file - https://kubernetes.io/docs/reference/kubectl/kubectl/#environment-variables
 - It also support merging of kubeconfigs

```
kubectl config --kubeconfig=config-demo view
```

### Helm
Has multiple config files but this makes it clear. 

```
helm --registry-config 
```

**Comment by shizhMSFT** [comment]
Since oras originally uses `--config` for credentials for registry access, `--registry-config` makes more senses.

**Comment by lizMSFT** [comment]
IMHO, I feel that it may depend on what is the purpose of the `--config` option. I checked the use of the `-c/--config` option, and currently it is used to specify an alternate location store credentials. By default, this will store credentials in `~/.docker/config.json`. (ref: https://oras.land/cli/0_authentication/).

I am not sure whether this configuration file is only for accessing credentials of repository in ORAS or not. If it is, then `--registry-config` seems make sense. However, if it is more like a client configuration for ORAS CLI, then maybe `--client-config` or `--oras-config` make more sense? Because it may also store other information like the sample in https://docs.docker.com/engine/reference/commandline/cli/#sample-configuration-file

**Comment by sajayantony** [comment]
@lizMSFT - that's a good point. Also I don't see that --oras-config would be passed in most cases. I've honestly never used that parameter so keeping that is mind having a longer name for the config makes sense since its not just registry settings and we can use it to store things about other settings like default cache and settings as well.
