### ISSUE TITLE
bug: `manifest fetch` fails when confirming the platform of a manifest

### ISSUE THREAD

**Issue by qweeah** [oras-project/oras#636]
# Reproduce step
```
oras manifest fetch ghcr.io/oras-project/oras@sha256:ec82a074d971186e5c47080b7eb35275e61f7c3be8303d1f891923d0109f239f --platform arm64/linux
# Error: sha256:bd06290a13e684209732bcfd5747f617b601e1d5fef1db0c07266546dd0941e7: not found
```

Root cause is that the a manifestStore is used for blob(config) fetching

**Comment by shizhMSFT** [comment]
Let's create a fix to `main`.

**Comment by yuehaoliang-microsoft** [comment]
Why applying `--platform arm64/linux` will fetch the config of this manifest?

**Comment by shizhMSFT** [comment]
> Why applying `--platform arm64/linux` will fetch the config of this manifest?

It will check the config file to confirm that it is indeed an image for arm64/linux.

**Comment by yuehaoliang-microsoft** [comment]
Thank you, I understand the root cause of this issue. I previously missed the fact that config file is fetched inside [this callee function](https://github.com/oras-project/oras-go/blob/9945bfb76605ae88fdc497dffa2bb7b4dbf25d8e/internal/platform/platform.go#L103). Here, the ReadOnlyTarget passed to it shouldn't be `ManifestStore` because it needs to fetch the blob.

**Comment by yuehaoliang-microsoft** [comment]
After the fix, the above error has been resolved.

<img width="856" alt="image" src="https://user-images.githubusercontent.com/109199020/194804207-9635b856-2446-4390-8a9e-bd220ad559e6.png">
