### ISSUE TITLE
support exclude digest tags in result of `oras repo tags`

### ISSUE THREAD

**Issue by qweeah** [oras-project/oras#658]
If a registry doesn't support referrer API natively, referrers will be tracked via client- maintained referrer tags following [schema](https://github.com/opencontainers/distribution-spec/blob/main/spec.md#referrers-tag-schema). 

User should be able to hide those tags in the result of `oras repo tags` via flag `--exclude-digest-tags`.

**Comment by sajayantony** [comment]
Is there a concern of showing the tags and filtering by —exclude-digest-tags? 
Over the course we should see less and less digest tags once registries implement it and I would say showing them in the default output might even encourage the operators to move.

**Comment by qweeah** [comment]
> Is there a concern of showing the tags and filtering by —exclude-digest-tags? Over the course we should see less and less digest tags once registries implement it and I would say showing them in the default output might even encourage the operators to move.

Updated.

**Comment by qweeah** [comment]
According to the [distribution spec](https://github.com/opencontainers/distribution-spec/blob/main/spec.md#referrers-tag-schema), a to-be-hidden tag is actually a `referrers tag`. I think it's better to name this flag to `--no-referrers`.

cc @FeynmanZhou Can you help confirm the naming?

**Comment by FeynmanZhou** [comment]
IMO, `·--no-referrers` is too technical for dummy users who are not familiar with OCI spec. It's not recommended that we borrow the terminology from [distribution spec](https://github.com/opencontainers/distribution-spec/blob/main/spec.md#referrers-tag-schema) directly since it is used for registry vendors/implementors instead of users.

If the purpose of this flag is filtering out the referrers tags from the tag list when the registry returns unavailable Referrers API, why not just use a simple flag name `--filter`?

**Comment by shizhMSFT** [comment]
`--filter` does sound a good name for me. It reminds me something like `oras repo tags --filter "v2.*" blablabla.io/blabla`.

**Comment by qweeah** [comment]
> `--filter` does sound a good name for me. It reminds me something like `oras repo tags --filter "v2.*" blablabla.io/blabla`.

What is the expected behavior for filtering out referrers tags? 

1) `oras repo tags --filter`
2) `oras repo tags --filter sha256[a-f0-9]*`

**Comment by qweeah** [comment]
I prefer the second one. Because we can even apply the filtering to `oras repo ls` and eventually `oras ls`.
