### ISSUE TITLE
oras attach on AWS ECR: Invalid JSON syntax

### ISSUE THREAD

**Issue by visit1985** [oras-project/oras#690]
### What happened in your environment?

When trying to add a file to an existing artefact in AWS ECR, I receive the following error:

Error: PUT "https://[account-id].dkr.ecr.[region].amazonaws.com/v2/repo/manifests/sha256:91fc7b16d3160baa1f1745968b917603f22a40cc75c8bda23b10d742be999388": response status code 405: unsupported: Invalid parameter at 'ImageManifest' failed to satisfy constraint: 'Invalid JSON syntax'

### How can we reproduce it?

1. Create an artefact

```
aws ecr get-login-password | oras push -u AWS --password-stdin [account-id].dkr.ecr.[region].amazonaws.com/repo:v1 --config config.json:application/vnd.acme.rocket.config artifact.txt:text/plain
```

2. Try to add another file to the artefact

```
aws ecr get-login-password | oras attach -u AWS --password-stdin --artifact-type doc/example [account-id].dkr.ecr.[region].amazonaws.com/repo:v1 hi.txt
```

### What is the version of your ORAS CLI?

0.16.0

### What is your OS environment?

Windows 10

### Are you willing to submit PRs to fix it?

- [ ] Yes, I am willing to fix it.

**Comment by visit1985** [comment]
Nevermind, AWS ECR does not support the ORAS Artefact Spec yet.
https://oras.land/cli/6_reference_types/#coming-soon-amazon-ecr

**Comment by SamirPS** [comment]
Does AWS ECR support ORAS Spec now ?

**Comment by WillSewell** [comment]
My understanding is `oras attach` relies on [attached artefacts](https://oras.land/docs/concepts/reftypes), which were only [added in OCI image spec v1.1](https://opencontainers.org/posts/blog/2023-07-07-summary-of-upcoming-changes-in-oci-image-and-distribution-specs-v-1-1/). However this version is not currently supported by ECR, see: https://github.com/oras-project/oras/issues/1133.

**Comment by jlbutler** [comment]
I opened a new issue to track what appears to be a regression from oras 1.0.  Attach in 1.0 worked with ECR, because it has an `--image-spec` option, similar to the one push still has. I added notes to the linked issue above (1133), push does work fine.

For posterity, ECR doesn't support 1.1 version image or distribution features yet because the specs are still pending in RC state. Once they are released and GA, ECR will move to supporting the features of those specs.
