### ISSUE TITLE
docker.io authentication issue

### ISSUE THREAD

**Issue by zosocanuck** [oras-project/oras#737]
### What happened in your environment?

Getting an authentication error when attempting to list repositories from docker.io:

`oras repo ls docker.io --username myusername --password mytoken`

`Error: GET "https://registry-1.docker.io/v2/_catalog": response status code 401: unauthorized: authentication required: [map[Action:* Class: Name:catalog Type:registry]]`

Note that I can successfully login from `docker login` as well as `oras login`

### What did you expect to happen?

Ability to list repositories

### How can we reproduce it?

Run the above command with the appropriate docker credentials

### What is the version of your ORAS CLI?

```
Version:    0.16.0+Homebrew
Go version: go1.19.3
```

### What is your OS environment?

MacOS

### Are you willing to submit PRs to fix it?

- [ ] Yes, I am willing to fix it.

**Comment by qweeah** [comment]
`oras repo ls` is built upon `/v2/catalog/` API (see [spec](https://docs.docker.com/registry/spec/api/#listing-repositories)) which lists ALL the repositories in a registry. Are you trying to list all the repositories in docker.io? I don't think that is doable for docker.io since your account won't have read access to other org's namespaces.

**Comment by qweeah** [comment]
I am not a Dockerhub expert but looks like they support account-level repository querying via a non-OCI API (/v2/repositories). @zosocanuck You may try https://github.com/docker/hub-tool with commands like `hub-tool repo ls <account>`.

**Comment by shizhMSFT** [comment]
Closing since DockerHub does not support catalog list.
