### ISSUE TITLE
Add filter to `oras repo tags` to filter by sha or tag

### ISSUE THREAD

**Issue by TerryHowe** [oras-project/oras#799]
### What is the version of your ORAS CLI

1.0.0

### What would you like to be added?

It would be convenient to have a filter for `oras repo tags` to get all the tags associated with a digest. Something like:
```
 oras repo tags ${REGISTRY}/curated-packages/prometheus/prometheus@sha256:c551125a624189cece9135981621f3f3144564ddabe14b523507bf74c2281d9b
```
Optionally, provide a tag and list other tags associated with the same tag
```
oras repo tags ${REGISTRY}/curated-packages/prometheus/prometheus:latest
```

### Why is this needed for ORAS?

I want to know the version of the latest or I want to know the version associated with a digest

### Are you willing to submit PRs to contribute to this feature?

- [x] Yes, I am willing to implement it.

**Comment by TerryHowe** [comment]
Implemented a simple WIP which works for digests.

**Comment by shizhMSFT** [comment]
The idea is great. However, we still need to consider the performance.

According to https://github.com/oras-project/oras/pull/800#discussion_r1105475134, `docker.io/library/alpine` has 129 tags. Filtering requires roughly 47 seconds. Since the time complexity is linear to the number of tags in the repository, it is estimated to take 6 mins to filter a repo of 1,000 tags.

As @qweeah has suggested, we may want to
1. Introduce `--concurreny` flag to accelerate the process.
2. Users need to be warned for long running command.
3. This feature is required to marked as experimental due to UX concerns.

**Comment by sajayantony** [comment]
There are throttling issues to consider since registries typically throttle the tag listing API. Also we should consider outputting a progress like curl so that users know that there is something happening rather than waiting for a long time. Higher concurrency may result in 429s easily.

**Comment by TerryHowe** [comment]
I order to support concurrency, most likely need to add support for it in oras-go https://github.com/oras-project/oras-go/issues/445

**Comment by shizhMSFT** [comment]
> I order to support concurrency, most likely need to add support for it in oras-go [oras-project/oras-go#445](https://github.com/oras-project/oras-go/issues/445)

Tag listing cannot be done in parallel but the process of resolving a tag to a digest can.

**Comment by qweeah** [comment]
> > I order to support concurrency, most likely need to add support for it in oras-go [oras-project/oras-go#445](https://github.com/oras-project/oras-go/issues/445)
> 
> Tag listing cannot be done in parallel but the process of resolving a tag to a digest can.

Does it mean oras-go will support resolving multiple references with tuned concurrency option in the future, and oras CLI can leverage that?
