### ISSUE TITLE
Enforce branch policies on the repository

### ISSUE THREAD

**Issue by toddysm** [oras-project/oras#862]
### What is the version of your ORAS CLI

n/a

### What would you like to be added?

To improve the security of the ORAS project we need to enforce the branch policies for this repository. I propose that we enforce the policies as follows:

- Use the following rules for `main` and `release/*` branches:
    - Require PR before merging
      - [ ] Require 3 approvals
      - [ ] Dismiss stale PR approvals when new commits are pushed
      - [x] Require review from Code Owners
      - [x] Require status checks to pass before merging
      - [x] Require conversation resolution before merging
      - [ ] Require signed commits
      - [ ] Do not allow bypass the above settings

Please add your comments and proposals for additional changes to this issue.

### Why is this needed for ORAS?

n/a

### Are you willing to submit PRs to contribute to this feature?

- [X] Yes, I am willing to implement it.

**Comment by shizhMSFT** [comment]
Few comments:
- The pattern `release-*` is adopted in this repository and thus `release/*` does not apply. Note that git may be in trouble if there is branch named `release` when you trying to have `release/xxx`.
- Requiring `3` approvals is not applicable to this repository since we only have 3 active code owners.
- Additionally, we require branches to be up to date before merging, which is useful but not captured in this issue.

**Comment by sajayantony** [comment]
Should we close this - 
<img width="594" alt="image" src="https://github.com/oras-project/oras/assets/1821104/d9bd6add-003f-4836-90bd-4889507c9903">
